### ISSUE TITLE
major works checklist

### ISSUE THREAD

**Issue by ghost** [arcaspai/arcaspai.github.io#1]
- [x] redirect the homepage from a page of [redder0125.github.io](https://redder0125.github.io/arcaspai)
- [x] making new layout
- [x] add outer links
- [x] add a welcome message and new SVG files of logotypes
- [ ] add avatar *shimeji* part ~~with AI or open sources~~
- [x] delete menu bar
- [x] think about how to use main website
- [x] Don't shout some comments like ["I hate this stupid job!"](https://youtu.be/Kze04Xo0ue0)

**Comment by redder0125** [comment]
1. I will use this website to introduction project and works.
1. I trying draw the blueprint in Figma, but I felt not needed it.
1. I think not need a shimeji part in this website, maybe.
